# Copyright (C) 2015-2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/nubia/nx512j/setup-makefiles.sh

LOCAL_VENDOR_PATH := vendor/nubia/nx512j/proprietary/vendor
LOCAL_VENDOR_GSI_PATH := vendor/nubia/nx512j/proprietary/GSI/vendor

PRODUCT_COPY_FILES += \
    $(LOCAL_VENDOR_PATH)/bin/adsprpcd:$(TARGET_COPY_OUT_VENDOR)/bin/adsprpcd \
    $(LOCAL_VENDOR_PATH)/bin/btnvtool:$(TARGET_COPY_OUT_VENDOR)/bin/btnvtool \
    $(LOCAL_VENDOR_PATH)/bin/hci_qcomm_init:$(TARGET_COPY_OUT_VENDOR)/bin/hci_qcomm_init \
    $(LOCAL_VENDOR_PATH)/bin/irsc_util:$(TARGET_COPY_OUT_VENDOR)/bin/irsc_util \
    $(LOCAL_VENDOR_PATH)/bin/mm-pp-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/mm-pp-daemon \
    $(LOCAL_VENDOR_PATH)/bin/mm-qcamera-app:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qcamera-app \
    $(LOCAL_VENDOR_PATH)/bin/mm-qcamera-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qcamera-daemon \
    $(LOCAL_VENDOR_PATH)/bin/msm_irqbalance:$(TARGET_COPY_OUT_VENDOR)/bin/msm_irqbalance \
    $(LOCAL_VENDOR_PATH)/bin/netmgrd:$(TARGET_COPY_OUT_VENDOR)/bin/netmgrd \
    $(LOCAL_VENDOR_PATH)/bin/qmuxd:$(TARGET_COPY_OUT_VENDOR)/bin/qmuxd \
    $(LOCAL_VENDOR_PATH)/bin/qseecomd:$(TARGET_COPY_OUT_VENDOR)/bin/qseecomd \
    $(LOCAL_VENDOR_PATH)/bin/radish:$(TARGET_COPY_OUT_VENDOR)/bin/radish \
    $(LOCAL_VENDOR_PATH)/bin/rmt_storage:$(TARGET_COPY_OUT_VENDOR)/bin/rmt_storage \
    $(LOCAL_VENDOR_PATH)/bin/time_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/time_daemon \
    $(LOCAL_VENDOR_PATH)/etc/capability.xml:$(TARGET_COPY_OUT_VENDOR)/etc/capability.xml \
    $(LOCAL_VENDOR_PATH)/firmware/a225_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225_pfp.fw \
    $(LOCAL_VENDOR_PATH)/firmware/a225_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225_pm4.fw \
    $(LOCAL_VENDOR_PATH)/firmware/a225p5_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225p5_pm4.fw \
    $(LOCAL_VENDOR_PATH)/firmware/a300_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pfp.fw \
    $(LOCAL_VENDOR_PATH)/firmware/a300_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pm4.fw \
    $(LOCAL_VENDOR_PATH)/firmware/a330_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a330_pfp.fw \
    $(LOCAL_VENDOR_PATH)/firmware/a330_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a330_pm4.fw \
    $(LOCAL_VENDOR_PATH)/firmware/a420_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pfp.fw \
    $(LOCAL_VENDOR_PATH)/firmware/a420_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pm4.fw \
    $(LOCAL_VENDOR_PATH)/firmware/cyttsp5_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cyttsp5_fw.bin \
    $(LOCAL_VENDOR_PATH)/firmware/ice40.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ice40.bin \
    $(LOCAL_VENDOR_PATH)/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    $(LOCAL_VENDOR_PATH)/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    $(LOCAL_VENDOR_PATH)/firmware/nfc_test.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nfc_test.bin \
    $(LOCAL_VENDOR_PATH)/firmware/venus.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b00 \
    $(LOCAL_VENDOR_PATH)/firmware/venus.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b01 \
    $(LOCAL_VENDOR_PATH)/firmware/venus.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b02 \
    $(LOCAL_VENDOR_PATH)/firmware/venus.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b03 \
    $(LOCAL_VENDOR_PATH)/firmware/venus.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b04 \
    $(LOCAL_VENDOR_PATH)/firmware/venus.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mbn \
    $(LOCAL_VENDOR_PATH)/firmware/venus.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mdt \
    $(LOCAL_VENDOR_PATH)/etc/permissions/com.qti.snapdragon.sdk.display.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.qti.snapdragon.sdk.display.xml \
    $(LOCAL_VENDOR_PATH)/etc/permissions/qcnvitems.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/qcnvitems.xml \
    $(LOCAL_VENDOR_PATH)/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/qcrilhook.xml \
    $(LOCAL_VENDOR_PATH)/framework/com.qti.snapdragon.sdk.display.jar:$(TARGET_COPY_OUT_VENDOR)/framework/com.qti.snapdragon.sdk.display.jar \
    $(LOCAL_VENDOR_PATH)/lib/hw/camera.msm8916.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.msm8916.so \
    $(LOCAL_VENDOR_PATH)/lib/libmm-qcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-qcamera.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_interface.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmjpeg_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg_interface.so \
    $(LOCAL_VENDOR_PATH)/lib/libmorpho_image_converter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmorpho_image_converter.so \
    $(LOCAL_VENDOR_PATH)/lib/libmorpho_jpeg_io.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmorpho_jpeg_io.so \
    $(LOCAL_VENDOR_PATH)/lib/libmorpho_memory_allocator.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmorpho_memory_allocator.so \
    $(LOCAL_VENDOR_PATH)/lib/libmorpho_strobe_photo_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmorpho_strobe_photo_jni.so \
    $(LOCAL_VENDOR_PATH)/lib/libnubia_runtime.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnubia_runtime.so \
    $(LOCAL_VENDOR_PATH)/lib/libnubia_servers.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnubia_servers.so \
    $(LOCAL_VENDOR_PATH)/lib/libnubia_trajectory.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnubia_trajectory.so \
    $(LOCAL_VENDOR_PATH)/lib/libobjectclear.so:$(TARGET_COPY_OUT_VENDOR)/lib/libobjectclear.so \
    $(LOCAL_VENDOR_PATH)/lib/libobjectclear_nubia.so:$(TARGET_COPY_OUT_VENDOR)/lib/libobjectclear_nubia.so \
    $(LOCAL_VENDOR_PATH)/lib/libqomx_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_core.so \
    $(LOCAL_VENDOR_PATH)/lib/libskia.so:$(TARGET_COPY_OUT_VENDOR)/lib/libskia.so \
    $(LOCAL_VENDOR_PATH)/lib64/libskia.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libskia.so \
    $(LOCAL_VENDOR_PATH)/lib64/libAlgorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libAlgorithm.so \
    $(LOCAL_VENDOR_PATH)/lib64/libBuffer.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libBuffer.so \
    $(LOCAL_VENDOR_PATH)/lib64/libFNVfbEngineLib.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libFNVfbEngineLib.so \
    $(LOCAL_VENDOR_PATH)/lib64/libIndependenceUtil.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libIndependenceUtil.so \
    $(LOCAL_VENDOR_PATH)/lib64/libNubiaImageAlgorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libNubiaImageAlgorithm.so \
    $(LOCAL_VENDOR_PATH)/lib64/libNubiaxmptoolkit.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libNubiaxmptoolkit.so \
    $(LOCAL_VENDOR_PATH)/lib64/libalRnB.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libalRnB.so \
    $(LOCAL_VENDOR_PATH)/lib64/libalSDE2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libalSDE2.so \
    $(LOCAL_VENDOR_PATH)/lib64/libavcodec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libavcodec.so \
    $(LOCAL_VENDOR_PATH)/lib64/libavfilter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libavfilter.so \
    $(LOCAL_VENDOR_PATH)/lib64/libavformat.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libavformat.so \
    $(LOCAL_VENDOR_PATH)/lib64/libavutil.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libavutil.so \
    $(LOCAL_VENDOR_PATH)/lib64/libbuffer_manager.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbuffer_manager.so \
    $(LOCAL_VENDOR_PATH)/lib64/libmorpho_image_converter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmorpho_image_converter.so \
    $(LOCAL_VENDOR_PATH)/lib64/libmorpho_jpeg_io.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmorpho_jpeg_io.so \
    $(LOCAL_VENDOR_PATH)/lib64/libmorpho_memory_allocator.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmorpho_memory_allocator.so \
    $(LOCAL_VENDOR_PATH)/lib64/libmorpho_panorama_gp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmorpho_panorama_gp.so \
    $(LOCAL_VENDOR_PATH)/lib64/libmulti_exposure.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmulti_exposure.so \
    $(LOCAL_VENDOR_PATH)/lib64/libnubia_clone.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnubia_clone.so \
    $(LOCAL_VENDOR_PATH)/lib64/libnubia_delay_recorder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnubia_delay_recorder.so \
    $(LOCAL_VENDOR_PATH)/lib64/libnubia_runtime.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnubia_runtime.so \
    $(LOCAL_VENDOR_PATH)/lib64/libnubia_servers.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnubia_servers.so \
    $(LOCAL_VENDOR_PATH)/lib64/libnubia_trajectory.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnubia_trajectory.so \
    $(LOCAL_VENDOR_PATH)/lib64/libnubiajpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnubiajpeg.so \
    $(LOCAL_VENDOR_PATH)/lib64/libobjectclear.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libobjectclear.so \
    $(LOCAL_VENDOR_PATH)/lib64/libobjectclear_nubia.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libobjectclear_nubia.so \
    $(LOCAL_VENDOR_PATH)/lib64/libpanoramahelper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpanoramahelper.so \
    $(LOCAL_VENDOR_PATH)/lib64/libproductinfo.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libproductinfo.so \
    $(LOCAL_VENDOR_PATH)/lib64/librilqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librilqmiservices.so \
    $(LOCAL_VENDOR_PATH)/lib64/libwcnss_qmi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libwcnss_qmi.so \
    $(LOCAL_VENDOR_PATH)/bin/perfd:$(TARGET_COPY_OUT_VENDOR)/bin/perfd \
    $(LOCAL_VENDOR_PATH)/bin/thermal-engine:$(TARGET_COPY_OUT_VENDOR)/bin/thermal-engine \
    $(LOCAL_VENDOR_PATH)/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    $(LOCAL_VENDOR_PATH)/firmware/BCM20795A1_001.002.012.0003.0104_Generic_I2C_NCD_Unsigned_configdata.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM20795A1_001.002.012.0003.0104_Generic_I2C_NCD_Unsigned_configdata.ncd \
    $(LOCAL_VENDOR_PATH)/firmware/BCM20795A2_001.003.025.0005.0035_Generic_I2C_NCD_Unsigned_configdata.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM20795A2_001.003.025.0005.0035_Generic_I2C_NCD_Unsigned_configdata.ncd \
    $(LOCAL_VENDOR_PATH)/lib/egl/eglSubDriverAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/eglSubDriverAndroid.so \
    $(LOCAL_VENDOR_PATH)/lib/egl/eglsubAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/eglsubAndroid.so \
    $(LOCAL_VENDOR_PATH)/lib/egl/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib/egl/libESXEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libESXEGL_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib/egl/libESXGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libESXGLESv1_CM_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib/egl/libESXGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libESXGLESv2_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib/egl/libGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib/egl/libGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib/egl/libQTapGLES.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libQTapGLES.so \
    $(LOCAL_VENDOR_PATH)/lib/egl/libRBEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libRBEGL_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib/egl/libRBGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libRBGLESv1_CM_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib/egl/libRBGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libRBGLESv2_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib/egl/libq3dtools_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libq3dtools_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib/hw/flp.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/flp.default.so \
    $(LOCAL_VENDOR_PATH)/lib/libC2D2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libC2D2.so \
    $(LOCAL_VENDOR_PATH)/lib/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib/libCB.so \
    $(LOCAL_VENDOR_PATH)/lib/libDivxDrm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libDivxDrm.so \
    $(LOCAL_VENDOR_PATH)/lib/libFlacSwDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libFlacSwDec.so \
    $(LOCAL_VENDOR_PATH)/lib/libI420colorconvert.so:$(TARGET_COPY_OUT_VENDOR)/lib/libI420colorconvert.so \
    $(LOCAL_VENDOR_PATH)/lib/libOmxAacDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxAacDec.so \
    $(LOCAL_VENDOR_PATH)/lib/libOmxAmrwbplusDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxAmrwbplusDec.so \
    $(LOCAL_VENDOR_PATH)/lib/libOmxEvrcDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxEvrcDec.so \
    $(LOCAL_VENDOR_PATH)/lib/libOmxMux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxMux.so \
    $(LOCAL_VENDOR_PATH)/lib/libOmxQcelp13Dec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxQcelp13Dec.so \
    $(LOCAL_VENDOR_PATH)/lib/libOmxWmaDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxWmaDec.so \
    $(LOCAL_VENDOR_PATH)/lib/libOpenCL.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenCL.so \
    $(LOCAL_VENDOR_PATH)/lib/libQSEEComAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libQSEEComAPI.so \
    $(LOCAL_VENDOR_PATH)/lib/libRSDriver_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/libRSDriver_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib/libSHIMDivxDrm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libSHIMDivxDrm.so \
    $(LOCAL_VENDOR_PATH)/lib/libTimeService.so:$(TARGET_COPY_OUT_VENDOR)/lib/libTimeService.so \
    $(LOCAL_VENDOR_PATH)/lib/libacdb-fts.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdb-fts.so \
    $(LOCAL_VENDOR_PATH)/lib/libacdbloader.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbloader.so \
    $(LOCAL_VENDOR_PATH)/lib/libacdbmapper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbmapper.so \
    $(LOCAL_VENDOR_PATH)/lib/libacdbrtac.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbrtac.so \
    $(LOCAL_VENDOR_PATH)/lib/libactuator_rohm_bu64297gwz.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_rohm_bu64297gwz.so \
    $(LOCAL_VENDOR_PATH)/lib/libactuator_rohm_bu64297gwz_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_rohm_bu64297gwz_camcorder.so \
    $(LOCAL_VENDOR_PATH)/lib/libactuator_rohm_bu64297gwz_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_rohm_bu64297gwz_camera.so \
    $(LOCAL_VENDOR_PATH)/lib/libadiertac.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadiertac.so \
    $(LOCAL_VENDOR_PATH)/lib/libadreno_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadreno_utils.so \
    $(LOCAL_VENDOR_PATH)/lib/libadsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadsprpc.so \
    $(LOCAL_VENDOR_PATH)/lib/libaudcal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudcal.so \
    $(LOCAL_VENDOR_PATH)/lib/libaudioalsa.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudioalsa.so \
    $(LOCAL_VENDOR_PATH)/lib/libc2d30-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d30-a3xx.so \
    $(LOCAL_VENDOR_PATH)/lib/libc2d30-a4xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d30-a4xx.so \
    $(LOCAL_VENDOR_PATH)/lib/libcalmodule_gyroscope.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcalmodule_gyroscope.so \
    $(LOCAL_VENDOR_PATH)/lib/libchromatix_imx179_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_common.so \
    $(LOCAL_VENDOR_PATH)/lib/libchromatix_imx179_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_default_video.so \
    $(LOCAL_VENDOR_PATH)/lib/libchromatix_imx179_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_preview.so \
    $(LOCAL_VENDOR_PATH)/lib/libchromatix_imx179_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx179_snapshot.so \
    $(LOCAL_VENDOR_PATH)/lib/libchromatix_imx234_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx234_common.so \
    $(LOCAL_VENDOR_PATH)/lib/libchromatix_imx234_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx234_default_video.so \
    $(LOCAL_VENDOR_PATH)/lib/libchromatix_imx234_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx234_hfr_120.so \
    $(LOCAL_VENDOR_PATH)/lib/libchromatix_imx234_hfr_240.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx234_hfr_240.so \
    $(LOCAL_VENDOR_PATH)/lib/libchromatix_imx234_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx234_liveshot.so \
    $(LOCAL_VENDOR_PATH)/lib/libchromatix_imx234_pre4zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx234_pre4zsl.so \
    $(LOCAL_VENDOR_PATH)/lib/libchromatix_imx234_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx234_preview.so \
    $(LOCAL_VENDOR_PATH)/lib/libchromatix_imx234_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx234_snapshot.so \
    $(LOCAL_VENDOR_PATH)/lib/libchromatix_imx234_snapshot_nightmode.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx234_snapshot_nightmode.so \
    $(LOCAL_VENDOR_PATH)/lib/libchromatix_imx234_snapshot_nightmode_1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx234_snapshot_nightmode_1.so \
    $(LOCAL_VENDOR_PATH)/lib/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdiag.so \
    $(LOCAL_VENDOR_PATH)/lib/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsi_netctrl.so \
    $(LOCAL_VENDOR_PATH)/lib/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsutils.so \
    $(LOCAL_VENDOR_PATH)/lib/libfastcvopt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfastcvopt.so \
    $(LOCAL_VENDOR_PATH)/lib/libgsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgsl.so \
    $(LOCAL_VENDOR_PATH)/lib/libhwdaphal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhwdaphal.so \
    $(LOCAL_VENDOR_PATH)/lib/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libidl.so \
    $(LOCAL_VENDOR_PATH)/lib/libjpegdhw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegdhw.so \
    $(LOCAL_VENDOR_PATH)/lib/libjpegehw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegehw.so \
    $(LOCAL_VENDOR_PATH)/lib/libllvm-glnext.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-glnext.so \
    $(LOCAL_VENDOR_PATH)/lib/libllvm-qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-qcom.so \
    $(LOCAL_VENDOR_PATH)/lib/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmdmdetect.so \
    $(LOCAL_VENDOR_PATH)/lib/libmm-color-convertor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-color-convertor.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmQSM.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmQSM.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera2_c2d_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_c2d_module.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera2_cpp_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_cpp_module.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera2_frame_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_frame_algorithm.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera2_iface_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_iface_modules.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera2_imglib_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_imglib_modules.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera2_is.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_is.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera2_isp_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_isp_modules.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera2_pproc_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_pproc_modules.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera2_q3a_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_q3a_core.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_algorithm.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera2_stats_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_modules.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera2_vpe_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_vpe_module.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera2_wnr_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_wnr_module.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera_faceproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_faceproc.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera_hdr_gb_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hdr_gb_lib.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera_hdr_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hdr_lib.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera_hi256.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hi256.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera_imglib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imglib.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera_imx179.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx179.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera_imx179_mcnex_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx179_mcnex_eeprom.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera_imx234.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx234.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera_imx234_bu64297gwz_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx234_bu64297gwz_eeprom.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera_tintless_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_algo.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera_tintless_bg_pca_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_bg_pca_algo.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmcamera_wavelet_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_wavelet_lib.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmipl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmipl.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmparser.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmparser.so \
    $(LOCAL_VENDOR_PATH)/lib/libmmqjpeg_codec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmqjpeg_codec.so \
    $(LOCAL_VENDOR_PATH)/lib/liboemcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcamera.so \
    $(LOCAL_VENDOR_PATH)/lib/liboemcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcrypto.so \
    $(LOCAL_VENDOR_PATH)/lib/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqcci_legacy.so \
    $(LOCAL_VENDOR_PATH)/lib/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdi.so \
    $(LOCAL_VENDOR_PATH)/lib/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdp.so \
    $(LOCAL_VENDOR_PATH)/lib/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi.so \
    $(LOCAL_VENDOR_PATH)/lib/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_cci.so \
    $(LOCAL_VENDOR_PATH)/lib/libqmi_client_helper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_helper.so \
    $(LOCAL_VENDOR_PATH)/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_qmux.so \
    $(LOCAL_VENDOR_PATH)/lib/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_common_so.so \
    $(LOCAL_VENDOR_PATH)/lib/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_csi.so \
    $(LOCAL_VENDOR_PATH)/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_encdec.so \
    $(LOCAL_VENDOR_PATH)/lib/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmiservices.so \
    $(LOCAL_VENDOR_PATH)/lib/libqomx_jpegdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegdec.so \
    $(LOCAL_VENDOR_PATH)/lib/libqomx_jpegenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc.so \
    $(LOCAL_VENDOR_PATH)/lib/libqti-iop-client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqti-iop-client.so \
    $(LOCAL_VENDOR_PATH)/lib/libqti-perfd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqti-perfd-client.so \
    $(LOCAL_VENDOR_PATH)/lib/librs_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib/librs_adreno_sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno_sha1.so \
    $(LOCAL_VENDOR_PATH)/lib/libsc-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsc-a3xx.so \
    $(LOCAL_VENDOR_PATH)/lib/libscale.so:$(TARGET_COPY_OUT_VENDOR)/lib/libscale.so \
    $(LOCAL_VENDOR_PATH)/lib/libsmemlog.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsmemlog.so \
    $(LOCAL_VENDOR_PATH)/lib/libstlport.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstlport.so \
    $(LOCAL_VENDOR_PATH)/lib/libthermalclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libthermalclient.so \
    $(LOCAL_VENDOR_PATH)/lib/libvoice-svc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvoice-svc.so \
    $(LOCAL_VENDOR_PATH)/lib/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib/libxml.so \
    $(LOCAL_VENDOR_PATH)/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so \
    $(LOCAL_VENDOR_PATH)/lib/qcdrm/playready/lib/drm/libdrmprplugin_customer.so:$(TARGET_COPY_OUT_VENDOR)/lib/qcdrm/playready/lib/drm/libdrmprplugin_customer.so \
    $(LOCAL_VENDOR_PATH)/lib/qcdrm/playready/lib/libprdrmdecrypt_customer.so:$(TARGET_COPY_OUT_VENDOR)/lib/qcdrm/playready/lib/libprdrmdecrypt_customer.so \
    $(LOCAL_VENDOR_PATH)/lib/qcdrm/playready/lib/libtzplayready_customer.so:$(TARGET_COPY_OUT_VENDOR)/lib/qcdrm/playready/lib/libtzplayready_customer.so \
    $(LOCAL_VENDOR_PATH)/lib/qcdrm/playready/lib/mediadrm/libprmediadrmdecrypt_customer.so:$(TARGET_COPY_OUT_VENDOR)/lib/qcdrm/playready/lib/mediadrm/libprmediadrmdecrypt_customer.so \
    $(LOCAL_VENDOR_PATH)/lib/qcdrm/playready/lib/mediadrm/libprmediadrmplugin_customer.so:$(TARGET_COPY_OUT_VENDOR)/lib/qcdrm/playready/lib/mediadrm/libprmediadrmplugin_customer.so \
    $(LOCAL_VENDOR_PATH)/lib/soundfx/libqcbassboost.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libqcbassboost.so \
    $(LOCAL_VENDOR_PATH)/lib/soundfx/libqcreverb.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libqcreverb.so \
    $(LOCAL_VENDOR_PATH)/lib/soundfx/libqcvirt.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libqcvirt.so \
    $(LOCAL_VENDOR_PATH)/lib64/egl/eglSubDriverAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/eglSubDriverAndroid.so \
    $(LOCAL_VENDOR_PATH)/lib64/egl/eglsubAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/eglsubAndroid.so \
    $(LOCAL_VENDOR_PATH)/lib64/egl/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libEGL_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib64/egl/libESXEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libESXEGL_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib64/egl/libESXGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libESXGLESv1_CM_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib64/egl/libESXGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libESXGLESv2_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib64/egl/libGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv1_CM_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib64/egl/libGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv2_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib64/egl/libQTapGLES.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libQTapGLES.so \
    $(LOCAL_VENDOR_PATH)/lib64/egl/libRBEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libRBEGL_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib64/egl/libRBGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libRBGLESv1_CM_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib64/egl/libRBGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libRBGLESv2_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib64/egl/libq3dtools_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libq3dtools_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib64/hw/flp.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/flp.default.so \
    $(LOCAL_VENDOR_PATH)/lib64/lib-sec-disp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-sec-disp.so \
    $(LOCAL_VENDOR_PATH)/lib64/libC2D2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libC2D2.so \
    $(LOCAL_VENDOR_PATH)/lib64/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libCB.so \
    $(LOCAL_VENDOR_PATH)/lib64/libDivxDrm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libDivxDrm.so \
    $(LOCAL_VENDOR_PATH)/lib64/libFlacSwDec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libFlacSwDec.so \
    $(LOCAL_VENDOR_PATH)/lib64/libOmxAacDec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libOmxAacDec.so \
    $(LOCAL_VENDOR_PATH)/lib64/libOmxMux.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libOmxMux.so \
    $(LOCAL_VENDOR_PATH)/lib64/libOpenCL.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libOpenCL.so \
    $(LOCAL_VENDOR_PATH)/lib64/libQSEEComAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libQSEEComAPI.so \
    $(LOCAL_VENDOR_PATH)/lib64/libRSDriver_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libRSDriver_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib64/libSHIMDivxDrm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libSHIMDivxDrm.so \
    $(LOCAL_VENDOR_PATH)/lib64/libSecureUILib.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libSecureUILib.so \
    $(LOCAL_VENDOR_PATH)/lib64/libStDrvInt.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libStDrvInt.so \
    $(LOCAL_VENDOR_PATH)/lib64/libTimeService.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libTimeService.so \
    $(LOCAL_VENDOR_PATH)/lib64/libacdb-fts.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdb-fts.so \
    $(LOCAL_VENDOR_PATH)/lib64/libacdbloader.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdbloader.so \
    $(LOCAL_VENDOR_PATH)/lib64/libacdbmapper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdbmapper.so \
    $(LOCAL_VENDOR_PATH)/lib64/libacdbrtac.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdbrtac.so \
    $(LOCAL_VENDOR_PATH)/lib64/libactuator_rohm_bu64297gwz.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libactuator_rohm_bu64297gwz.so \
    $(LOCAL_VENDOR_PATH)/lib64/libactuator_rohm_bu64297gwz_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libactuator_rohm_bu64297gwz_camcorder.so \
    $(LOCAL_VENDOR_PATH)/lib64/libactuator_rohm_bu64297gwz_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libactuator_rohm_bu64297gwz_camera.so \
    $(LOCAL_VENDOR_PATH)/lib64/libadiertac.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadiertac.so \
    $(LOCAL_VENDOR_PATH)/lib64/libadreno_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadreno_utils.so \
    $(LOCAL_VENDOR_PATH)/lib64/libadsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadsprpc.so \
    $(LOCAL_VENDOR_PATH)/lib64/libaudcal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudcal.so \
    $(LOCAL_VENDOR_PATH)/lib64/libaudioalsa.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudioalsa.so \
    $(LOCAL_VENDOR_PATH)/lib64/libbtnv.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbtnv.so \
    $(LOCAL_VENDOR_PATH)/lib64/libc2d30-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libc2d30-a3xx.so \
    $(LOCAL_VENDOR_PATH)/lib64/libc2d30-a4xx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libc2d30-a4xx.so \
    $(LOCAL_VENDOR_PATH)/lib64/libcalmodule_akm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcalmodule_akm.so \
    $(LOCAL_VENDOR_PATH)/lib64/libcalmodule_gyroscope.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcalmodule_gyroscope.so \
    $(LOCAL_VENDOR_PATH)/lib64/libchromatix_imx179_common.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx179_common.so \
    $(LOCAL_VENDOR_PATH)/lib64/libchromatix_imx179_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx179_default_video.so \
    $(LOCAL_VENDOR_PATH)/lib64/libchromatix_imx179_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx179_preview.so \
    $(LOCAL_VENDOR_PATH)/lib64/libchromatix_imx179_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx179_snapshot.so \
    $(LOCAL_VENDOR_PATH)/lib64/libchromatix_imx234_common.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx234_common.so \
    $(LOCAL_VENDOR_PATH)/lib64/libchromatix_imx234_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx234_default_video.so \
    $(LOCAL_VENDOR_PATH)/lib64/libchromatix_imx234_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx234_hfr_120.so \
    $(LOCAL_VENDOR_PATH)/lib64/libchromatix_imx234_hfr_240.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx234_hfr_240.so \
    $(LOCAL_VENDOR_PATH)/lib64/libchromatix_imx234_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx234_liveshot.so \
    $(LOCAL_VENDOR_PATH)/lib64/libchromatix_imx234_pre4zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx234_pre4zsl.so \
    $(LOCAL_VENDOR_PATH)/lib64/libchromatix_imx234_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx234_preview.so \
    $(LOCAL_VENDOR_PATH)/lib64/libchromatix_imx234_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx234_snapshot.so \
    $(LOCAL_VENDOR_PATH)/lib64/libchromatix_imx234_snapshot_nightmode.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx234_snapshot_nightmode.so \
    $(LOCAL_VENDOR_PATH)/lib64/libchromatix_imx234_snapshot_nightmode_1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx234_snapshot_nightmode_1.so \
    $(LOCAL_VENDOR_PATH)/lib64/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libconfigdb.so \
    $(LOCAL_VENDOR_PATH)/lib64/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdiag.so \
    $(LOCAL_VENDOR_PATH)/lib64/libdisp-aba.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdisp-aba.so \
    $(LOCAL_VENDOR_PATH)/lib64/libdrmfs.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmfs.so \
    $(LOCAL_VENDOR_PATH)/lib64/libdrmtime.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmtime.so \
    $(LOCAL_VENDOR_PATH)/lib64/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdsi_netctrl.so \
    $(LOCAL_VENDOR_PATH)/lib64/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdsutils.so \
    $(LOCAL_VENDOR_PATH)/lib64/libgsl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgsl.so \
    $(LOCAL_VENDOR_PATH)/lib64/libhwdaphal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhwdaphal.so \
    $(LOCAL_VENDOR_PATH)/lib64/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libidl.so \
    $(LOCAL_VENDOR_PATH)/lib64/libllvm-glnext.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libllvm-glnext.so \
    $(LOCAL_VENDOR_PATH)/lib64/libllvm-qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libllvm-qcom.so \
    $(LOCAL_VENDOR_PATH)/lib64/liblqe.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblqe.so \
    $(LOCAL_VENDOR_PATH)/lib64/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmdmdetect.so \
    $(LOCAL_VENDOR_PATH)/lib64/libmm-abl-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-abl-oem.so \
    $(LOCAL_VENDOR_PATH)/lib64/libmm-abl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-abl.so \
    $(LOCAL_VENDOR_PATH)/lib64/libmm-als.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-als.so \
    $(LOCAL_VENDOR_PATH)/lib64/libmm-disp-apis.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-disp-apis.so \
    $(LOCAL_VENDOR_PATH)/lib64/libmm-hdcpmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-hdcpmgr.so \
    $(LOCAL_VENDOR_PATH)/lib64/libmm-qdcm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-qdcm.so \
    $(LOCAL_VENDOR_PATH)/lib64/libmmcamera2_frame_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera2_frame_algorithm.so \
    $(LOCAL_VENDOR_PATH)/lib64/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera2_stats_algorithm.so \
    $(LOCAL_VENDOR_PATH)/lib64/libmmparser.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmparser.so \
    $(LOCAL_VENDOR_PATH)/lib64/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnetmgr.so \
    $(LOCAL_VENDOR_PATH)/lib64/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libperipheral_client.so \
    $(LOCAL_VENDOR_PATH)/lib64/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqcci_legacy.so \
    $(LOCAL_VENDOR_PATH)/lib64/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqdi.so \
    $(LOCAL_VENDOR_PATH)/lib64/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqdp.so \
    $(LOCAL_VENDOR_PATH)/lib64/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi.so \
    $(LOCAL_VENDOR_PATH)/lib64/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_cci.so \
    $(LOCAL_VENDOR_PATH)/lib64/libqmi_client_helper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_client_helper.so \
    $(LOCAL_VENDOR_PATH)/lib64/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_client_qmux.so \
    $(LOCAL_VENDOR_PATH)/lib64/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_common_so.so \
    $(LOCAL_VENDOR_PATH)/lib64/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_csi.so \
    $(LOCAL_VENDOR_PATH)/lib64/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_encdec.so \
    $(LOCAL_VENDOR_PATH)/lib64/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmiservices.so \
    $(LOCAL_VENDOR_PATH)/lib64/libqti-iop-client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqti-iop-client.so \
    $(LOCAL_VENDOR_PATH)/lib64/libqti-perfd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqti-perfd-client.so \
    $(LOCAL_VENDOR_PATH)/lib64/libril-qc-ltedirectdisc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-ltedirectdisc.so \
    $(LOCAL_VENDOR_PATH)/lib64/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-qmi-1.so \
    $(LOCAL_VENDOR_PATH)/lib64/libril-qc-radioconfig.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-radioconfig.so \
    $(LOCAL_VENDOR_PATH)/lib64/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qcril-hook-oem.so \
    $(LOCAL_VENDOR_PATH)/lib64/librpmb.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librpmb.so \
    $(LOCAL_VENDOR_PATH)/lib64/librs_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librs_adreno.so \
    $(LOCAL_VENDOR_PATH)/lib64/librs_adreno_sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librs_adreno_sha1.so \
    $(LOCAL_VENDOR_PATH)/lib64/libsc-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsc-a3xx.so \
    $(LOCAL_VENDOR_PATH)/lib64/libscale.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libscale.so \
    $(LOCAL_VENDOR_PATH)/lib64/libsecureui.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsecureui.so \
    $(LOCAL_VENDOR_PATH)/lib64/libsecureui_svcsock.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsecureui_svcsock.so \
    $(LOCAL_VENDOR_PATH)/lib64/libsettings.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsettings.so \
    $(LOCAL_VENDOR_PATH)/lib64/libsmemlog.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsmemlog.so \
    $(LOCAL_VENDOR_PATH)/lib64/libssd.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libssd.so \
    $(LOCAL_VENDOR_PATH)/lib64/libsystem_health_mon.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsystem_health_mon.so \
    $(LOCAL_VENDOR_PATH)/lib64/libthermalclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libthermalclient.so \
    $(LOCAL_VENDOR_PATH)/lib64/libthermalioctl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libthermalioctl.so \
    $(LOCAL_VENDOR_PATH)/lib64/libvoice-svc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvoice-svc.so \
    $(LOCAL_VENDOR_PATH)/lib64/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libxml.so \
    $(LOCAL_VENDOR_PATH)/lib64/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib64/mediadrm/libwvdrmengine.so \
    $(LOCAL_VENDOR_PATH)/lib64/qcdrm/playready/lib/libtzplayready_customer.so:$(TARGET_COPY_OUT_VENDOR)/lib64/qcdrm/playready/lib/libtzplayready_customer.so \
    $(LOCAL_VENDOR_PATH)/lib64/qcdrm/playready/lib/mediadrm/libprmediadrmplugin_customer.so:$(TARGET_COPY_OUT_VENDOR)/lib64/qcdrm/playready/lib/mediadrm/libprmediadrmplugin_customer.so

# GPS-blobs (kang from xiaomi_msm8953-common)
PRODUCT_COPY_FILES += \
    $(LOCAL_VENDOR_PATH)/bin/hw/vendor.qti.gnss@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.qti.gnss@1.0-service \
    $(LOCAL_VENDOR_PATH)/etc/init/vendor.qti.gnss@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.gnss@1.0-service.rc \
    $(LOCAL_VENDOR_PATH)/bin/loc_launcher:$(TARGET_COPY_OUT_VENDOR)/bin/loc_launcher \
    $(LOCAL_VENDOR_PATH)/bin/lowi-server:$(TARGET_COPY_OUT_VENDOR)/bin/lowi-server \
    $(LOCAL_VENDOR_PATH)/bin/slim_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/slim_daemon \
    $(LOCAL_VENDOR_PATH)/bin/xtra-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/xtra-daemon \
    $(LOCAL_VENDOR_PATH)/etc/cacert_location.pem:$(TARGET_COPY_OUT_VENDOR)/etc/cacert_location.pem \
    $(LOCAL_VENDOR_PATH)/etc/xtra_root_cert.pem:$(TARGET_COPY_OUT_VENDOR)/etc/xtra_root_cert.pem \
    $(LOCAL_VENDOR_PATH)/lib64/hw/vendor.qti.gnss@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/vendor.qti.gnss@1.0-impl.so \
    $(LOCAL_VENDOR_PATH)/lib64/libalarmservice_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libalarmservice_jni.so \
    $(LOCAL_VENDOR_PATH)/lib64/libdataitems.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdataitems.so \
    $(LOCAL_VENDOR_PATH)/lib64/libdrplugin_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrplugin_client.so \
    $(LOCAL_VENDOR_PATH)/lib64/libDRPlugin.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libDRPlugin.so \
    $(LOCAL_VENDOR_PATH)/lib64/libevent_observer.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libevent_observer.so \
    $(LOCAL_VENDOR_PATH)/lib64/libflp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libflp.so \
    $(LOCAL_VENDOR_PATH)/lib64/libgdtap.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgdtap.so \
    $(LOCAL_VENDOR_PATH)/lib64/libgeofence.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgeofence.so \
    $(LOCAL_VENDOR_PATH)/lib64/libizat_client_api.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libizat_client_api.so \
    $(LOCAL_VENDOR_PATH)/lib64/libizat_core.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libizat_core.so \
    $(LOCAL_VENDOR_PATH)/lib64/liblbs_core.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblbs_core.so \
    $(LOCAL_VENDOR_PATH)/lib64/libloc_ds_api.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libloc_ds_api.so \
    $(LOCAL_VENDOR_PATH)/lib64/libloc_externalDr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libloc_externalDr.so \
    $(LOCAL_VENDOR_PATH)/lib64/liblocationservice_glue.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblocationservice_glue.so \
    $(LOCAL_VENDOR_PATH)/lib64/liblocationservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblocationservice.so \
    $(LOCAL_VENDOR_PATH)/lib64/liblowi_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblowi_client.so \
    $(LOCAL_VENDOR_PATH)/lib64/liblowi_wifihal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblowi_wifihal.so \
    $(LOCAL_VENDOR_PATH)/lib64/libquipc_os_api.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libquipc_os_api.so \
    $(LOCAL_VENDOR_PATH)/lib64/libsensor1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsensor1.so \
    $(LOCAL_VENDOR_PATH)/lib64/libulp2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libulp2.so \
    $(LOCAL_VENDOR_PATH)/lib64/libxtadapter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libxtadapter.so \
    $(LOCAL_VENDOR_PATH)/lib64/libxtwifi_ulp_adaptor.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libxtwifi_ulp_adaptor.so \
    $(LOCAL_VENDOR_PATH)/lib64/vendor.qti.gnss@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.gnss@1.0.so \
    $(LOCAL_VENDOR_PATH)/lib64/libqdma_file_agent.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqdma_file_agent.so

# ANT-blobs (kang from xiaomi_msm8953-common)
PRODUCT_COPY_FILES += \
    $(LOCAL_VENDOR_PATH)/lib64/com.qualcomm.qti.ant@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.qualcomm.qti.ant@1.0.so

# QTI BT blobs (kang from xiaomi_msm8953-common)
PRODUCT_COPY_FILES += \
    $(LOCAL_VENDOR_PATH)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    $(LOCAL_VENDOR_PATH)/bin/hw/android.hardware.bluetooth@1.0-service-qti:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.bluetooth@1.0-service-qti \
    $(LOCAL_VENDOR_PATH)/bin/wcnss_filter:$(TARGET_COPY_OUT_VENDOR)/bin/wcnss_filter \
    $(LOCAL_VENDOR_PATH)/lib64/hw/android.hardware.bluetooth@1.0-impl-qti.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/android.hardware.bluetooth@1.0-impl-qti.so \
    $(LOCAL_VENDOR_PATH)/lib64/libbt-hidlclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbt-hidlclient.so \
    $(LOCAL_VENDOR_PATH)/lib64/vendor.qti.hardware.fm@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.fm@1.0.so

# More shared Vulkan blobs
PRODUCT_COPY_FILES += \
    $(LOCAL_VENDOR_PATH)/lib/egl/libq3dtools_esx.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libq3dtools_esx.so \
    $(LOCAL_VENDOR_PATH)/lib64/egl/libq3dtools_esx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libq3dtools_esx.so \
    $(LOCAL_VENDOR_PATH)/lib/hw/vulkan.msm8916.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vulkan.msm8916.so \
    $(LOCAL_VENDOR_PATH)/lib64/hw/vulkan.msm8916.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/vulkan.msm8916.so \
    $(LOCAL_VENDOR_PATH)/lib/libbccQTI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbccQTI.so \
    $(LOCAL_VENDOR_PATH)/lib64/libbccQTI.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbccQTI.so \
    $(LOCAL_VENDOR_PATH)/lib/libllvm-qgl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-qgl.so \
    $(LOCAL_VENDOR_PATH)/lib64/libllvm-qgl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libllvm-qgl.so

# Add missing prebuilt libraries from /system for Lineage OS based GSIs
PRODUCT_COPY_FILES += \
    $(LOCAL_VENDOR_GSI_PATH)/lib/libaudioroute.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudioroute.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/libaudioroute.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudioroute.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib/libcap.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcap.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/libcap.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcap.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib/libminijail.so:$(TARGET_COPY_OUT_VENDOR)/lib/libminijail.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/libminijail.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libminijail.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib/libpuresoftkeymasterdevice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpuresoftkeymasterdevice.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/libpuresoftkeymasterdevice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpuresoftkeymasterdevice.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib/android.hardware.soundtrigger@2.0-core.so:$(TARGET_COPY_OUT_VENDOR)/lib/android.hardware.soundtrigger@2.0-core.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/android.hardware.usb@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.usb@1.0.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/vendor.lineage.livedisplay@2.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.lineage.livedisplay@2.0.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/vendor.lineage.trust@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.lineage.trust@1.0.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib/android.hardware.radio.deprecated@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/android.hardware.radio.deprecated@1.0.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/android.hardware.radio.deprecated@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.radio.deprecated@1.0.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/android.hardware.wifi@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.wifi@1.0.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/android.hardware.wifi@1.1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.wifi@1.1.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/android.hardware.wifi@1.2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.wifi@1.2.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/android.hardware.wifi.supplicant@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.wifi.supplicant@1.0.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/android.hardware.wifi.supplicant@1.1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.wifi.supplicant@1.1.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/android.hardware.wifi.hostapd@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.wifi.hostapd@1.0.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib/libfmjni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfmjni.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/libfmjni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfmjni.so

# Add missing prebuilt libraries from /system for AOSP based GSIs
PRODUCT_COPY_FILES += \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/libbfqio.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbfqio.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib/vendor.lineage.power@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.lineage.power@1.0.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/vendor.lineage.power@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.lineage.power@1.0.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib/vendor.lineage.camera.motor@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.lineage.camera.motor@1.0.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/vendor.lineage.camera.motor@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.lineage.camera.motor@1.0.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib/android.hardware.radio@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/android.hardware.radio@1.0.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/android.hardware.radio@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.radio@1.0.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib/android.hardware.radio@1.1.so:$(TARGET_COPY_OUT_VENDOR)/lib/android.hardware.radio@1.1.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/android.hardware.radio@1.1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.radio@1.1.so

# Add missing prebuilt libraries from /system for Pixel Experience based GSIs (Havoc, Arrow, Evolution-X)
PRODUCT_COPY_FILES += \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/libnl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnl.so

# Add Legacy HAL1 Camera's prebuilt libraries from /system for GSIs (it will be enabled with adaptation patch)
PRODUCT_COPY_FILES += \
    $(LOCAL_VENDOR_GSI_PATH)/bin/mediaserver:$(TARGET_COPY_OUT_VENDOR)/bin/mediaserver \
    $(LOCAL_VENDOR_GSI_PATH)/lib/libcameraservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcameraservice.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/libcameraservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcameraservice.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib/libstagefright_omx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_omx.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/libstagefright_omx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libstagefright_omx.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib/libstagefright_omx_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_omx_utils.so \
    $(LOCAL_VENDOR_GSI_PATH)/lib64/libstagefright_omx_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libstagefright_omx_utils.so



PRODUCT_PACKAGES += \
    libloc_api_v02 \
    libtime_genoff \
    TimeService \
    colorservice \
    shutdownlistener \
    qcrilmsgtunnel \
    qcnvitems \
    qcrilhook
